services:
  ylem:
    image: "ardemylem/ylem:ylem"
    entrypoint: ["/opt/ylem/start_ylem.sh"]
    env_file:
      - .env
    container_name: ylem
    ports:
      - "7332:7332" # Statistics
      - "7333:7333" # Users
      - "7336:7336" # Pipelines
      - "7339:7339" # API
    stdin_open: true
    tty: true
    volumes:
      - ./.env:/opt/ylem/api/.env
      - ./.env:/opt/ylem/backend/pipelines/.env
      - ./.env:/opt/ylem/backend/statistics/.env
      - ./.env:/opt/ylem/backend/users/.env
      - ./start_ylem.sh:/opt/ylem/start_ylem.sh
    networks:
      - ylem_network
    depends_on:
      ylem_database:
        condition: service_healthy
      ylem_statistics_database:
        condition: service_healthy
      # Comment this one out if you use your own Apache Kafka cluster
      ylem_kafka_topic_creator:
        condition: service_completed_successfully

  ylem_taskrunner:
    image: "ardemylem/ylem:taskrunner"
    entrypoint: ["/opt/ylem/start_taskrunner.sh"]
    env_file:
      - .env
    container_name: ylem_taskrunner
    ports:
      - "7334:7335" # Load balancer
      - "7335:7335" # Task runner
      - "7337:7337" # Integrations
    stdin_open: true
    tty: true
    volumes:
      - ./.env:/opt/ylem/backend/integrations/.env
      - ./.env:/opt/ylem/processor/taskrunner/.env
      - ./start_taskrunner.sh:/opt/ylem/start_taskrunner.sh
      - ./keys:/opt/ylem/backend/integrations/config/keys
      - ./keys:/opt/ylem/processor/taskrunner/config/keys
    networks:
      - ylem_network
    depends_on:
      ylem_database:
        condition: service_healthy
      ylem_statistics_database:
        condition: service_healthy
      # Comment this one out if you use your own Apache Kafka cluster
      ylem_kafka_topic_creator:
        condition: service_completed_successfully

  ylem_session_storage:
    image: "ardemylem/ylem:session_storage"
    env_file:
      - .env
    command: redis-server --requirepass ${YLEM_REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./database/session_data:/data
    networks:
      - ylem_network
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: ylem_session_storage
    links:
      - ylem_database
    depends_on:
      ylem_database:
        condition: service_healthy

  ylem_python_processor:
    image: "ardemylem/ylem:python_processor"
    container_name: ylem_python_processor
    networks:
      - ylem_network
    ports:
      - "7338:7338"
    stdin_open: true
    tty: true

  ylem_ui:
    image: "ardemylem/ylem:ui"
    container_name: ylem_ui
    networks:
      - ylem_network
    ports:
      - "7440:7440"
    stdin_open: true

  ylem_router:
    image: "ardemylem/ylem:router"
    container_name: ylem_router
    networks:
      - ylem_network
    depends_on:
      - ylem
      - ylem_ui
    volumes:
      - ./router-logs:/var/log
    ports:
      - "7331:7331"
      - "443:443"

  ylem_database:
    image: "ardemylem/ylem:database"
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
    networks:
      - ylem_network
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
    container_name: ylem_database
    healthcheck:
      interval: 10s
      retries: 50
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 15s

  ylem_statistics_database:
    image: "ardemylem/ylem:statistics_database"
    networks:
      - ylem_network
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./database/statistics_data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    container_name: ylem_statistics_database
    healthcheck:
      interval: 10s
      retries: 50
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1
      timeout: 15s

  # Comment this one out if you use your own Apache Kafka cluster
  ylem_kafka_broker:
    image: confluentinc/confluent-local:7.7.1
    container_name: ylem_kafka_broker
    networks:
      - ylem_network
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_YLEM://ylem_kafka_broker:39092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_YLEM:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://localhost:29092,CONTROLLER://localhost:29093,PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_YLEM://ylem_kafka_broker:39092"
    ports:
      - "39092:39092"
    volumes:
      - ./database/kafka_data:/var/lib/kafka/data
    healthcheck:
      test: /bin/kafka-topics --list --bootstrap-server localhost:9092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60
  ylem_kafka_topic_creator:
    image: confluentinc/confluent-local:7.7.1
    container_name: ylem_kafka_topic_creator
    networks:
      - ylem_network
    depends_on:
      ylem_kafka_broker:
        condition: service_healthy
    command: "bash -c 'kafka-topics --create --if-not-exists --bootstrap-server ylem_kafka_broker:39092 --partitions 1 --replication-factor 1 --topic task_runs && \
                       kafka-topics --create --if-not-exists --bootstrap-server ylem_kafka_broker:39092 --partitions 1 --replication-factor 1 --topic task_runs_load_balanced && \
                       kafka-topics --create --if-not-exists --bootstrap-server ylem_kafka_broker:39092 --partitions 1 --replication-factor 1 --topic task_run_results && \
                       kafka-topics --create --if-not-exists --bootstrap-server ylem_kafka_broker:39092 --partitions 1 --replication-factor 1 --topic query_task_run_results && \
                       kafka-topics --create --if-not-exists --bootstrap-server ylem_kafka_broker:39092 --partitions 1 --replication-factor 1 --topic notification_task_run_results'"

networks:
  ylem_network:
    name: ylem_network
    external: false
